#############################################################################
# Makefile for building: Rcount-distribute.app/Contents/MacOS/Rcount-distribute
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Feb 11 11:53:17 2015
# Project:  p502dataAnalysisRNA.pro
# Template: app
# Command: /opt/local/bin/qmake -spec /opt/local/share/qt4/mkspecs/macx-xcode -o Rcount-distribute.xcodeproj/project.pbxproj p502dataAnalysisRNA.pro
#############################################################################

MOC       = /opt/local/bin/moc
UIC       = /opt/local/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/opt/local/share/qt4/mkspecs/macx-xcode -I. -I. -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local/include -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/opt/local/Library/Frameworks -F/opt/local/lib
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./moc_bamhandler.cpp ./moc_readmapper.cpp ./moc_readcounter.cpp\
	 ./moc_dataanalysis.cpp ./moc_createprojectwidget.cpp ./moc_projecttreeview.cpp\
	 ./moc_projecttreeviewmodel.cpp ./moc_resulttableviewmodel.cpp ./moc_resulttableview.cpp\
	 ./moc_dataanalysisview.cpp ./moc_analysisprogressview.cpp ./moc_consoleRunner.cpp ./ui_projecttreeview.h ./ui_createprojectwidget.h ./ui_resulttableview.h\
	 ./ui_analysisprogressview.h
compiler_objective_cxx_make_all:
compiler_objective_cxx_clean:
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_bamhandler.cpp moc_readmapper.cpp moc_readcounter.cpp moc_dataanalysis.cpp moc_createprojectwidget.cpp moc_projecttreeview.cpp moc_projecttreeviewmodel.cpp moc_resulttableviewmodel.cpp moc_resulttableview.cpp moc_dataanalysisview.cpp moc_analysisprogressview.cpp moc_consoleRunner.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_bamhandler.cpp moc_readmapper.cpp moc_readcounter.cpp moc_dataanalysis.cpp moc_createprojectwidget.cpp moc_projecttreeview.cpp moc_projecttreeviewmodel.cpp moc_resulttableviewmodel.cpp moc_resulttableview.cpp moc_dataanalysisview.cpp moc_analysisprogressview.cpp moc_consoleRunner.cpp
moc_bamhandler.cpp: ../seqan/bam_io.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/bamHandler/bamhandler.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_SOURCE/bamHandler/bamhandler.h -o moc_bamhandler.cpp

moc_readmapper.cpp: ../p502_SOURCE/dataStructure/databaseitem.h \
		../p502_SOURCE/dataStructure/database.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/dataAnalysis/readmapper.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_SOURCE/dataAnalysis/readmapper.h -o moc_readmapper.cpp

moc_readcounter.cpp: ../p502_SOURCE/dataStructure/databaseitem.h \
		../p502_SOURCE/dataStructure/database.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/dataStructure/temporaryresults.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataAnalysis/readcounter.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_SOURCE/dataAnalysis/readcounter.h -o moc_readcounter.cpp

moc_dataanalysis.cpp: ../p502_SOURCE/dataStructure/databaseitem.h \
		../p502_SOURCE/dataStructure/database.h \
		../p502_SOURCE/bamHandler/bamhandler.h \
		../seqan/bam_io.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/dataAnalysis/readmapper.h \
		../p502_SOURCE/dataAnalysis/readcounter.h \
		../p502_SOURCE/dataStructure/temporaryresults.h \
		../p502_SOURCE/dataAnalysis/dataanalysis.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_SOURCE/dataAnalysis/dataanalysis.h -o moc_dataanalysis.cpp

moc_createprojectwidget.cpp: ../p502_GUI/createProjectWidget/createprojectwidget.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/createProjectWidget/createprojectwidget.h -o moc_createprojectwidget.cpp

moc_projecttreeview.cpp: ../p502_GUI/projectTreeViewWidget/projecttreeview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/projectTreeViewWidget/projecttreeview.h -o moc_projecttreeview.cpp

moc_projecttreeviewmodel.cpp: ../p502_GUI/projectTreeViewWidget/projecttreeviewmodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/projectTreeViewWidget/projecttreeviewmodel.h -o moc_projecttreeviewmodel.cpp

moc_resulttableviewmodel.cpp: ../p502_GUI/resultTableViewWidget/resulttableviewmodel.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/resultTableViewWidget/resulttableviewmodel.h -o moc_resulttableviewmodel.cpp

moc_resulttableview.cpp: ../p502_GUI/resultTableViewWidget/resulttableviewmodel.h \
		../p502_GUI/resultTableViewWidget/resulttableview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/resultTableViewWidget/resulttableview.h -o moc_resulttableview.cpp

moc_dataanalysisview.cpp: ../p502_SOURCE/dataAnalysis/dataanalysis.h \
		../p502_SOURCE/dataStructure/databaseitem.h \
		../p502_SOURCE/dataStructure/database.h \
		../p502_SOURCE/bamHandler/bamhandler.h \
		../seqan/bam_io.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/dataAnalysis/readmapper.h \
		../p502_SOURCE/dataAnalysis/readcounter.h \
		../p502_SOURCE/dataStructure/temporaryresults.h \
		../p502_GUI/dataAnalysisViewWidget/dataanalysisview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/dataAnalysisViewWidget/dataanalysisview.h -o moc_dataanalysisview.cpp

moc_analysisprogressview.cpp: ../p502_GUI/analysisProgressWidget/analysisprogressview.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../p502_GUI/analysisProgressWidget/analysisprogressview.h -o moc_analysisprogressview.cpp

moc_consoleRunner.cpp: ../p502_SOURCE/dataAnalysis/dataanalysis.h \
		../p502_SOURCE/dataStructure/databaseitem.h \
		../p502_SOURCE/dataStructure/database.h \
		../p502_SOURCE/bamHandler/bamhandler.h \
		../seqan/bam_io.h \
		../p502_SOURCE/bamHandler/bamhelpers.h \
		../p502_SOURCE/dataStructure/mappingtreeitem.h \
		../p502_SOURCE/dataAnalysis/readmapper.h \
		../p502_SOURCE/dataAnalysis/readcounter.h \
		../p502_SOURCE/dataStructure/temporaryresults.h \
		consoleRunner.h
	/opt/local/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ consoleRunner.h -o moc_consoleRunner.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_projecttreeview.h ui_createprojectwidget.h ui_resulttableview.h ui_analysisprogressview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_projecttreeview.h ui_createprojectwidget.h ui_resulttableview.h ui_analysisprogressview.h
ui_projecttreeview.h: ../p502_GUI/projectTreeViewWidget/projecttreeview.ui
	/opt/local/bin/uic ../p502_GUI/projectTreeViewWidget/projecttreeview.ui -o ui_projecttreeview.h

ui_createprojectwidget.h: ../p502_GUI/createProjectWidget/createprojectwidget.ui
	/opt/local/bin/uic ../p502_GUI/createProjectWidget/createprojectwidget.ui -o ui_createprojectwidget.h

ui_resulttableview.h: ../p502_GUI/resultTableViewWidget/resulttableview.ui
	/opt/local/bin/uic ../p502_GUI/resultTableViewWidget/resulttableview.ui -o ui_resulttableview.h

ui_analysisprogressview.h: ../p502_GUI/analysisProgressWidget/analysisprogressview.ui
	/opt/local/bin/uic ../p502_GUI/analysisProgressWidget/analysisprogressview.ui -o ui_analysisprogressview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

